version: 2
jobs:
  node8:
    docker:
      - image: node:8-alpine
    steps:
      - run: apk add --no-cache make bash ca-certificates
      - checkout
      - restore_cache:
          keys:
          - node8-dependencies-{{ checksum "yarn.lock" }}
          - node8-dependencies-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: node8-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn test
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports
          destination: reports
  node9:
    docker:
      - image: node:9-alpine
    steps:
      - run: apk add --no-cache make bash ca-certificates
      - checkout
      - restore_cache:
          keys:
          - node9-dependencies-{{ checksum "yarn.lock" }}
          - node9-dependencies-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: node9-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn test
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports
          destination: reports
  node10:
    docker:
      - image: node:10-alpine
    steps:
      - run: apk add --no-cache make bash ca-certificates
      - checkout
      - restore_cache:
          keys:
          - node10-dependencies-{{ checksum "yarn.lock" }}
          - node10-dependencies-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: node10-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn test
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports
          destination: reports
workflows:
  version: 2
  build:
    jobs:
      - node8
      - node9
      - node10
